### ISSUE TITLE
Cannot create new node using ssh-key

### ISSUE THREAD

**Issue by jofan** [kontena/kontena-plugin-digitalocean#36]
Tried creating new digital ocean node after installing the digital ocean plugin.
This is the command I ran:

```
kontena digitalocean node create \
--token <redacted> \
--ssh-key ~/.ssh/ah_admin.pub \
--size 4gb \
--region ams2
```

I got an error saying that the ssh-key "are invalid key identifiers for Droplet creation."

After consulting with jakolehm on Slack I tried without the --ssh-key flag and everything worked.

**Comment by kke** [comment]
~~Which plugin version?~~ NVM, seems to do it with latest.


`kontena plugin list`

**Comment by kke** [comment]
Seems to work now with version 0.3.2 

https://github.com/kontena/kontena-plugin-digitalocean/releases/tag/v0.3.2
